# Акулова Анастасия Алексеевна ИУ5-65Б РК2, Вариант 1

Так как датасет boston был удален из библиотеки по причине "расизма", пришлось находить его содержимое самостоятельно и записывать в csv таблицу.

In [58]:
import pandas as pd
from sklearn.svm import SVR
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score

In [59]:
data = pd.read_csv('load_boston.csv')
data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [60]:
data.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [61]:
TARGET_KEY = 'MEDV'
X_data, y_data = data.drop(columns=[TARGET_KEY]), data[[TARGET_KEY]]
X_test, X_train, y_test, y_train = train_test_split(X_data, y_data)

In [62]:
svr = SVR(kernel='linear')
svr.fit(X_train, y_train)
svr_pred = svr.predict(X_test)
svr_pred

/home/pahan/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([27.07904178, 14.25515965, 11.15370125, 15.17916578, 20.16278968,
       10.7044408 , 15.13285949, 19.14525503, 26.85894192, 11.30209232,
       21.77787026, 19.0143049 , 37.97628359, 11.30778458, 23.65711244,
       11.48811097, 24.1297715 , 26.99125743, 39.75390677, 17.85259347,
       19.8405302 , 20.65565569, 34.99816616, 26.42539729, 29.91107311,
       20.39362142, 20.93463136, 12.94741371, 35.50461475, 19.76622288,
       23.31728711, 21.40533023, 21.64308834, 19.68320169,  9.96051572,
       16.73250482, 20.75433955, 16.2624671 , 19.49112791, 19.4442706 ,
       12.19729864, 31.18154114, 21.59232747, 23.13693392, 27.23394208,
       34.7935121 , 19.5613052 , 22.039825  , 36.59173625, 21.95383904,
       27.52765277, 19.03861764, 18.21746555, 30.21578241, 33.01474837,
       31.0798848 , 25.01019894, 13.46295799, 14.17609326, 15.00380488,
       20.74385851, 23.15050266, 29.22156154, 22.29222358, 22.76527029,
       17.93316129,  8.23034423, 23.64332201,  7.46753169, 19.08930764,
       27.84817291, -1.16226007, 31.09430864, 16.9492776 ,  5.80300423,
       14.10612516, 16.16930821, 23.67231346, 26.71678   , 25.79388561,
       32.45314122, 20.80519713, 21.19162665, 16.30206565, 11.9719043 ,
       38.02383482, 16.27411304, 26.80125524, 16.13907509, 27.1651168 ,
        4.62276746, 25.6682393 , 29.42659852, 30.00257733, 26.7061836 ,
       39.61565233, 25.32437532, 14.11579462, 11.22188089, 18.48528389,
       15.01158933, -3.06831027, 18.91415091, 18.13505271, 19.80238173,
       17.29322047, 13.86411063, 40.73910513,  4.0423246 ,  7.64831483,
       14.30839598, 29.80576435, 32.40138515, 26.50039397, 28.99672742,
       34.01305318, 30.56768618, 13.45832478, 20.17939565, 16.3476681 ,
       20.92062274, 33.3154045 , 17.93699446, 32.20081105, 17.89014592,
       26.15972226, 32.16878728, 27.86822668, 15.69985811, 12.49442008,
       29.71093469, 19.94032992, 20.97210311, 30.21210195, 18.69776246,
       17.98946144, 22.69072637, 30.73585466, 25.62041342, 11.0460002 ,
       22.39305817, 22.13797973, 17.66006369, 24.42753061, 30.01151059,
       20.5089725 , 18.63177973, 14.89342105, 14.4071535 , 30.4748523 ,
       17.00924634, 31.07949403, 22.10860513, 27.12591834, 24.02448739,
       15.81909344, 11.66526837, 15.77218442, 14.75725147,  9.33779241,
       34.24441762, 16.49438583, 16.33178923, 35.46547447, 12.25685256,
       10.47742032,  5.69740467, 18.10373565, 20.23217732, 33.48929263,
       16.45654158, 27.57302732, 11.69305949, 41.91421684, 21.58350228,
       18.0053591 , 26.11208671, 15.3524052 , 24.85975988, 19.09751584,
       17.24113777, 15.18101533, 27.53637984, 15.01479533, 24.92943831,
       21.54001425, 31.15225685, 22.06945823, 28.90910694, 25.10614193,
       21.1363661 , 12.72622809, 22.32862494, 17.38038345, 17.45249118,
       17.90656709, 23.82860412, 13.31659118, 39.44542853, 20.17036327,
       17.90077977, 30.04594295, 22.68044847, 15.28480176, 17.17616777,
       24.92931022, 32.88645547,  4.78530967, 15.02725165, 32.4280526 ,
       27.53198501, 25.06208856, 16.12363563, 38.52744503,  8.50332983,
       14.09816946, 37.18637609, 20.43163294, 27.34705893, 13.44510816,
       37.79462621, 16.86018706, 26.86549191, 38.68174063, 20.02578634,
       26.31119989, 18.92714377, 20.66574265, 27.7545056 , 21.46751771,
       18.0527934 , 19.05994195, 25.53573649, 23.99126179, 21.91098571,
       26.14773522, 14.30014676, 33.9585221 , 20.54457949, 24.79848108,
       18.79255176, 17.54759046, 24.92423455, 12.57688987, 13.95054791,
       18.89499481, 38.51285142, 26.34057319, 30.33118214, 18.54736502,
       20.81012169, 19.35926618, 19.72883137, 17.25006231, 28.61760176,
       16.43544945, 23.63790592, 16.14894973, 23.38451714, 33.10228184,
       24.70666211, 27.99453311, 24.20048225, 25.74766575, 14.23834104,
       22.26229073, 27.98975346, 20.4556409 , 17.32907016, 20.62791997,
       25.12273926, 32.23453716, 29.51689602, 16.79837451, 28.17507592,
       18.87470079, 13.68731227, 24.97530359, 15.51524686, 24.46393306,
       26.99866572, 20.12451409, 25.02837137, 35.24639425, 22.27438542,
       13.27669759, 16.30108075, 16.5289307 , 37.66022554, 31.77539427,
       20.83159114, 14.25934478, 21.44767343, 25.2760973 , 17.76855095,
       22.42732487, 24.70088691, 15.93388506, 22.1666851 , 24.10171033,
       15.36196953, 12.46089401, 25.82210124, 17.55942295, 11.90238294,
       14.17212602, 14.06857034, 27.49709583, 24.05055111, 23.06369134,
       20.59928618, -1.29109167, 23.64546944, 25.52041002, 18.8275149 ,
       14.2028707 , 26.76532785, 11.422255  , 37.25044697, 21.99527695,
       37.14382771, 24.38032245, 24.156682  ,  4.09436864, 21.17571406,
       15.07795011, 10.08617291, 28.14001565, 30.07474968, 25.3554825 ,
       22.35155554, 17.06644097, 30.26499277, 20.63272554, 27.99784716,
       17.82455449, 35.95865951,  2.75206918, 27.54863366, 27.79921911,
       35.97014303, 12.78205771, 22.25020396, 31.00810889, 20.13562824,
       23.96214893, 31.81428715, 13.08360067,  3.98685183, 19.47881181,
       17.60793443, 13.61824141, 29.4156581 , 16.82580762, 15.04529573,
       17.74785943, 15.05565407, 11.10939686, 19.77549479, 34.67710735,
       36.5831067 , 30.02484329, 31.34042333, 17.16584709,  9.77720589,
       19.23403351, 22.64926672, 14.26019528, 14.15604691, 25.65525868,
       16.56324305, 28.18282459, 24.48928864, 23.36352861, 24.81715833,
       13.13206664, 22.44161934, 14.95478076, 23.601942  ])

In [63]:
gb = GradientBoostingRegressor()
gb.fit(X_train, y_train)
gb_pred = gb.predict(X_test)
gb_pred

/home/pahan/.local/lib/python3.10/site-packages/sklearn/ensemble/_gb.py:437: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([24.1899355 , 16.22195329,  6.3405633 , 16.03135488, 21.35466338,
       15.3650441 , 19.64562209, 21.91569922, 26.00767878, 17.82438119,
       26.54013607, 21.76773184, 44.63654867, 11.19736749, 22.31904406,
       15.20724717, 21.31591506, 30.2026488 , 44.9427353 , 17.98492572,
       19.17196947, 21.20630762, 33.95586889, 24.34781231, 31.74745277,
       20.19588123, 19.85310906, 19.48643716, 33.51490784, 29.53022432,
       18.37547703, 18.81343347, 19.37220705, 19.5402495 , 18.90160002,
       16.33022551, 18.20944353, 16.21641157, 19.21109085, 20.03224769,
       19.43098835, 27.97565939, 28.95322378, 23.68555921, 25.46093076,
       32.91278094, 22.64848436, 23.60027978, 43.09395965, 20.67181352,
       38.20323157, 16.0204376 , 18.2640669 , 27.14153492, 39.58170144,
       33.12442413, 22.50067587, 12.72384415, 17.82272505,  8.43179366,
       22.2444698 , 21.0508208 , 30.14379859, 27.08686402, 22.19019639,
       18.78270563,  9.46134835, 23.33168762, 28.45849834, 19.8403021 ,
       25.48752745,  8.55071391, 35.00676847, 21.48892632,  7.67682194,
       12.61860991, 15.55796608, 22.73341009, 25.87922185, 32.13330633,
       34.30159138, 20.92524372, 19.79281489, 18.76513368, 15.14878742,
       44.73864028, 17.04812618, 23.29610064, 16.2334763 , 22.29904178,
       12.39766809, 25.58474514, 26.74546385, 31.06463312, 24.07855201,
       43.30144423, 24.15448871, 18.72935056, 15.25379016, 21.84552796,
       14.82462044,  7.9000356 , 17.62573126, 17.98184407, 21.07800058,
       16.09816769, 11.30434352, 44.43164059,  9.35687845,  6.86468571,
       16.52568608, 32.88352119, 40.41819071, 23.47661973, 26.51853848,
       36.01223803, 33.36794602, 14.51772507, 21.08446822, 16.04354061,
       21.06447058, 39.98912989, 17.30765582, 36.2698044 , 20.36455818,
       27.90263093, 35.87112241, 27.70810492, 15.61160548,  8.86991461,
       31.09867522, 20.8591585 , 21.13231642, 28.36443828, 11.66142471,
       24.54982775, 22.52474121, 30.92392025, 27.29763179, 11.85587379,
       23.84363099, 19.24200642, 18.8975254 , 22.93854142, 27.53559871,
       20.67694289, 24.19245968, 20.26758404, 12.19061813, 27.43075886,
       23.62486379, 32.61173345, 19.99754086, 26.97058152, 28.32920129,
       12.53999678, 12.88604011, 18.20579807, 22.91598613,  9.15053885,
       34.69927693, 21.85856534, 15.04685429, 42.88203332, 15.90941602,
        8.38235355,  8.39732916, 19.07128526, 19.84584715, 32.97713013,
       10.29845083, 24.72862768, 14.08861545, 48.05222781, 21.96925146,
       18.09420036, 25.32027587, 10.24222513, 23.25658435, 20.6210228 ,
       16.94561972, 18.28197835, 33.15824254,  8.80707837, 26.67252153,
       20.61119824, 31.92988474, 20.02594334, 34.65743221, 22.35126235,
       22.03471908, 16.07125419, 19.95107928, 17.13580907, 15.55429229,
       19.04934517, 22.71654978, 14.36369631, 48.62215403, 19.08006915,
       17.05758416, 29.76966185, 22.78685957, 17.82147934, 19.36346399,
       26.81623967, 36.30828671,  7.65373631, 18.61685129, 36.48114903,
       27.56337057, 24.32913519, 12.53193626, 43.85240924, 10.44489828,
       16.49583574, 49.60668273, 20.42786733, 22.86343014, 14.451165  ,
       43.94701531,  9.57489388, 28.06748955, 50.45982603, 20.82821907,
       26.12324762, 22.24880779, 22.28519679, 30.6524281 , 25.20195117,
       18.15192024, 20.39037042, 25.819379  , 23.25795789, 21.6246669 ,
       25.1693094 , 17.0357912 , 41.72391865, 19.82354205, 23.96098118,
       21.83041231, 19.20685885, 21.9260175 , 10.76356   , 16.20360254,
       19.96406044, 44.48551912, 29.05204096, 30.39489004, 17.43261812,
       21.95893299, 25.39197238, 19.3214696 , 14.72617863, 30.85607759,
       16.55036414, 23.93615903, 19.89918912, 16.99935589, 32.22168426,
       23.23914394, 31.36661527, 24.65926524, 24.23857252, 14.70875052,
       22.75020076, 30.05059687, 21.9291394 , 21.24334262, 17.35355635,
       22.29286476, 38.48397297, 29.7704398 , 15.6797764 , 28.81143481,
       17.86390972, 13.82754284, 30.57198446, 15.98970987, 23.36366749,
       27.48270263, 20.63649083, 24.11491649, 43.57114451, 19.2075042 ,
       13.74560131, 12.85546341, 21.57399257, 42.96940908, 31.58890407,
       17.25221462, 15.11492058, 22.38609484, 23.69471034, 18.82665681,
       23.9738928 , 25.27320291, 20.49443051, 23.59834743, 22.24037981,
       16.52516954, 27.13483685, 23.78203386, 13.59013156, 15.3994862 ,
       18.00236837, 18.25969641, 24.92445071, 23.37655745, 19.99097593,
       20.79069461,  9.13022605, 21.96566211, 23.83401453, 21.26136923,
       14.64513973, 23.97107702, 15.21533986, 48.10227887, 23.10595539,
       43.62453845, 23.96356896, 24.43000195, 14.23974287, 22.29396439,
       17.91693557, 16.16484112, 26.63796111, 30.47694223, 40.69799513,
       21.1190441 , 12.3755601 , 34.33435582, 26.37717538, 24.17692373,
       14.66352249, 49.15412744,  9.40499489, 26.99152736, 24.24745593,
       42.76854569, 16.37950141, 20.71377409, 35.09359992, 20.2156642 ,
       26.76407376, 36.31671972, 12.607688  ,  8.12125208, 18.05919135,
       19.50167316, 16.22618137, 30.99914449, 12.90859182, 19.9901964 ,
       20.35497441, 17.03675499, 17.62148773, 16.2936094 , 44.11894584,
       44.32548053, 35.1078754 , 30.68462782, 22.63889012, 12.11857013,
       19.35754664, 21.40383193, 16.26328091, 14.49389824, 24.73441199,
       17.78754254, 32.57758239, 24.85623607, 23.53136296, 24.5865413 ,
       14.56493167, 19.46417269, 13.91497013, 13.88912278])

Для сравнения качества моделей используем метрики средней абсолютной ошибки и коэффициента детерминации. Первый покажет, насколько предсказанные значения отклоняются от настоящих. Второй покажет, насколько точно модель предсказывает значения в целом.

In [64]:
svr_mae = mean_absolute_error(y_test, svr_pred)
gb_mae = mean_absolute_error(y_test, gb_pred)

In [65]:
svr_r2 = r2_score(y_test, svr_pred)
gb_r2 = r2_score(y_test, gb_pred)

In [66]:
pd.DataFrame.from_dict({
    'SVR': {
        'MAE': round(svr_mae, 5),
        'R2': f'{round(svr_r2 * 100, 3)}%'
    },
    'GB': {
        'MAE': round(gb_mae, 5),
        'R2': f'{round(gb_r2 * 100, 3)}%'
    }
})

         SVR       GB
MAE  3.35934  2.65826
R2   67.081%  81.366%

По результатам можно сказать, что модели можно признать приемлемыми. Также можно заметить, что градиентный бустинг справляется с задачей намного лучше, выдавая хорошие результаты.